services:
  api:
    image: ghcr.io/nikleban/carstockmarketbe:main
    pull_policy: always
    container_name: my-api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EVALUATION_URL: ${EVALUATION_URL}
    volumes:
      - uploads-data:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - vrooom

  frontend:
    image: ghcr.io/nikleban/carstockmarketfe:master
    pull_policy: always
    container_name: frontend
    networks:
      - vrooom

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /root/vrooom/docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 12
    networks:
      - vrooom

  redis:
    image: redis:7-alpine
    container_name: redis
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 12
    networks:
      - vrooom

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    networks:
      - vrooom
    ports:
      - 1025:1025
      - 8025:8025

  evaluation:
    image: ghcr.io/nikleban/carstockmarketevaluation:main
    pull_policy: always
    container_name: evaluation
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - vrooom

volumes:
  postgres-data:
  uploads-data:

networks:
  vrooom:
