import Brand from '#/models/Brand.js';
import CarModel from '#/models/CarModel.js';
import { createRequire } from 'module';

const MISSING_BRANDS_AND_MODELS = {
  BMW: ['1 Series', '2 Series', '4 Series', '7 Series', '8 Series', 'Z4Z4'],
  Volkswagen: [
    'up!',
    'Touran',
    'Caddy',
    'Sharan',
    'Tayron',
    'Taigo',
    'Transporter',
    'T-Roc',
    'T-Cross',
    'Polo',
    'Amarok',
    'Multivan',
    'California',
  ],
  Audi: ['A1', 'A2', 'Q2'],
  Toyota: [
    '4-Runner',
    'Auris',
    'Avalon',
    'Avensis',
    'Avensis Verso',
    'Aygo',
    'Aygo X',
    'bZ4X',
    'C-HR',
    'C-HR+',
    'Camry',
    'Carina',
    'Celica',
    'Corolla',
    'Corolla Cross',
    'Corolla Verso',
    'Crown',
    'FJ',
    'GR Yaris',
    'GR86',
    'GT86',
    'Hilux',
    'HiAce',
    'Highlander',
    'IQ',
    'Land Cruiser',
    'Mirai',
    'MR2',
    'LiteAce',
    'Paseo',
    'Picnic',
    'Previa',
    'Prius',
    'Proace (vsi)',
    'Proace Verso',
    'Proace City Verso',
    'RAV4',
    'Starlet',
    'Supra',
    'Tercel',
    'Urban Cruiser',
    'Verso',
    'Verso-S',
    'Yaris',
    'Yaris Cross',
    'Yaris Verso',
  ],
  Renault: [
    'Scenic',
    'Modus',
    'Austral',
    'Clio',
    'Meganetechno',
    'Twingo',
    'Megane',
    'Captur',
    'Talisman',
    'ZoeBose',
    'LagunaElite',
    'LagunaPrivil',
    'LagunaExpression',
    'Espaced',
    'R4',
    'Koleos',
    'SymbiozE',
    'Kadjar',
    'Kangoo',
    'Fluence',
    'Thalia',
  ],
  Peugeot: [
    '104',
    '106',
    '107',
    '108',
    '1007',
    '204',
    '205',
    '206',
    '207',
    '208',
    '2008',
    '301',
    '304',
    '305',
    '306',
    '307',
    '308',
    '309',
    '3008',
    'E-3008',
    '404',
    '405',
    '406',
    '407',
    '408',
    '4007',
    '4008',
    '504',
    '505',
    '508',
    '5008',
    'E-5008',
    '604',
    '605',
    '607',
    '806',
    '807',
    'Bipper',
    'Expert',
    'iOn',
    'Partner',
    'Pick Up',
    'RCZ',
    'Rifter',
    'Traveller',
  ],
  Ford: [
    'Aerostar',
    'Bronco',
    'B-Max',
    'C-Max (vsi)',
    'C-Max',
    'Grand C-Max',
    'Capri',
    'Cougar',
    'Ecosport',
    'Edge',
    'Escort',
    'Excursion',
    'Expedition',
    'Explorer',
    'Explorer EV',
    'F-150',
    'Fiesta',
    'Focus',
    'Fusion',
    'Galaxy',
    'Granada',
    'FordGT',
    'Ka',
    'Kuga',
    'Maverick',
    'Mondeo',
    'Mustang',
    'Mustang Mach-E',
    'Orion',
    'Probe',
    'Puma',
    'Ranger',
    'S-Max',
    'Scorpio',
    'Sierra',
    'StreetKa',
    'Taunus',
    'Taurus',
    'Thunderbird',
    'Tourneo',
    'Tourneo Courier',
    'Tourneo Connect',
    'Tourneo Custom',
    'Transit',
    'Transit Custom',
    'Windstar',
  ],
  'Mercedes-Benz': [
    '190',
    'W123',
    'AMG GT (vsi)',
    'AMG GT Coupe',
    'AMG GT Roadster',
    'AMG GT 4-vratni Coupe',
    'AMG One',
    'A-Razred',
    'B-Razred',
    'C-Razred',
    'Citan',
    'CL-Razred',
    'CLA-Razred (vsi)',
    'CLA-Razred',
    'CLA Shooting Brake',
    'CLC-Razred',
    'CLE-Razred',
    'CLK-Razred',
    'CLS-Razred (vsi)',
    'CLS-Razred',
    'CLS Shooting Brake',
    'E-Razred',
    'EQA',
    'EQB',
    'EQC',
    'EQE',
    'EQE',
    'EQS',
    'EQS SUV',
    'EQT',
    'EQV',
    'G-Razred',
    'GL-Razred',
    'GLA-Razred',
    'GLB-Razred',
    'GLC-Razred',
    'GLC coupe',
    'GLE-Razred',
    'GLE coupe',
    'GLK-Razred',
    'GLS-Razred',
    'ML-Razred',
    'R-Razred',
    'S-Razred',
    'SL-Razred',
    'SLC-Razred',
    'SLS AMG',
    'SLK-Razred',
    'SLR-Razred',
    'T-Razred',
    'V-Razred',
    'VLE-Razred',
    'Vaneo',
    'Viano',
    'Vito',
    'X-Razred',
  ],
  Citroën: [
    '2 CV',
    'Ami',
    'AX',
    'Berlingo',
    'BX',
    'C1',
    'C2',
    'C3',
    'C3 Aircross',
    'C3 Picasso',
    'C3 Pluriel',
    'C4',
    'C4 Aircross',
    'C4 Cactus',
    'C4 Picasso (vsi)',
    'C4 Picasso',
    'C4 Grand Picasso',
    'C4 SpaceTourer (vsi)',
    'C4 SpaceTourer',
    'C4 Grand SpaceTourer',
    'C4 X',
    'C5',
    'C5 Aircross',
    'C5 X',
    'C6',
    'C8',
    'C-Crosser',
    'C-Elysee',
    'C-Zero',
    'CX',
    'CitroenDS',
    'DS3',
    'DS4',
    'DS5',
    'Dyane',
    'Evasion',
    'GS',
    'GSA',
    'Jumpy',
    'LN',
    'Nemo',
    'Saxo',
    'SM',
    'SpaceTourer',
    'Visa',
    'Xantia',
    'CitroenXM',
    'Xsara',
    'Xsara Picasso',
    'ZX',
  ],
};

async function seedBrandsAndModels() {
  const require = createRequire(import.meta.url);
  const rows = require('./all-vehicles-model.json');

  const makes = new Map();
  for (const row of rows) {
    const make = row.make?.trim();
    const model = row.model?.trim();
    if (!make || !model) continue;
    if (!makes.has(make)) makes.set(make, new Set());
    makes.get(make).add(model);
  }

  for (const [brand, models] of Object.entries(MISSING_BRANDS_AND_MODELS)) {
    if (!makes.has(brand)) makes.set(brand, new Set());
    for (const model of models) makes.get(brand).add(model);
  }

  const brandRows = [...makes.keys()].map((name) => ({ name }));
  await Brand.bulkCreate(brandRows, { ignoreDuplicates: true });

  const brands = await Brand.findAll({ attributes: ['id', 'name'] });
  const brandIdByName = new Map(brands.map((b) => [b.name, b.id]));

  const modelRows = [];
  for (const [makeName, modelSet] of makes) {
    const brandId = brandIdByName.get(makeName);
    if (!brandId) continue;
    for (const modelName of modelSet) {
      modelRows.push({ name: modelName, brandId });
    }
  }

  await CarModel.bulkCreate(modelRows, {
    ignoreDuplicates: true,
    conflictFields: ['name', 'brandId'],
  });
  console.log(`Seeded ${brandRows.length} brands and ${modelRows.length} models.`);
}

seedBrandsAndModels();
